### ISSUE TITLE
Question about how to generate tof map in 'pcl' stream mode

### ISSUE THREAD

**Issue by hugoycj** [point-spread/OkuloSdk#2]
Thank you for your great work. I am currently using this SDK for tesing rgb-d based reconstruction. However, I met a problem that in 'pcl' mode, only the 'xyz', 'infrared', and 'color' were generated. It seems that 'xyz' is a colormap instead of raw depth map, which means that it loses the scale information. 

I wonder if it is possible to export depth map in pcl mode. Thanks for your reply.

**Comment by linhaigoo** [comment]
Sorry for confusing. The 'xyz' is a float32_t mat with three channel which holds the cordinates of all point clouds (unit : m).You may refer code below to get the depth map
`std::vector<cv::Mat> channels(3);
cv::split(xyz, channels);
const cv::Mat &depth = channels[2];
cv::Mat u16Depth;
depth.convertTo(u16Depth, CV_16UC1, 65535.0 / 7.5f);`
Notice that the depth map has been converted to uint16_t, since float32_t greater than 1.0 will be truncated in openCV when display or save.
Thans for your issue, we may complete the example in later version.
